name: "Deploy recipes"

on:
  workflow_dispatch:
  # push:
  #   branches: ["main"]
  #   paths: # only run on changes to feedstock relevant code
  #     - 'feedstock/**'
  #     - 'configs/**'
  #     - '.github/workflows/deploy.yaml'
  pull_request:
    branches: ["main"]
    paths: # only run on changes to feedstock relevant code
      - 'feedstock/**'
      - 'configs/**'
      - '.github/workflows/deploy.yaml'
  # schedule:
  #   - cron: "10 */7 * * *"   # runs 00:10, 07:10, 14:10, 21:10 (UTC)

jobs:
  deploy-recipes:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    name: deploy-recipes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v5
      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v3"
        with:
          credentials_json: "${{ secrets.GCP_DATAFLOW_SERVICE_KEY }}"
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install Runner
        run: python -m pip install pangeo-forge-runner==0.10.2
      - name: Install dependencies
        run: python -m pip install -r feedstock/requirements.txt
      - name: "Deploy recipes PR"
        if: ${{ github.event_name == 'pull_request' }}
        run: pangeo-forge-runner bake --repo=. -f=./configs/config-pgf-runner-leap-dataflow-pr.json
        env:
          IS_TEST: true
          IS_LOCAL: false
          GOOGLE_APPLICATION_CREDENTIALS: "${{ steps.auth.outputs.credentials_file_path }}"
      - name: "Deploy recipes Production"
        if: ${{ github.event_name != 'pull_request' }}
        run: pangeo-forge-runner bake --repo=. -f=./configs/config-pgf-runner-leap-dataflow.json
        env:
          IS_TEST: false
          IS_LOCAL: false
          GOOGLE_APPLICATION_CREDENTIALS: "${{ steps.auth.outputs.credentials_file_path }}"
