name: "Recipe CI w/o deployment"

on:
  pull_request:
    branches: ["main"]
    types: [opened, reopened, synchronize, labeled]
    paths: # only run on changes to feedstock relevant code
      - 'feedstock/**'
      - 'configs/**'
      - '.github/workflows/deploy.yaml'

jobs:
  recipe-ci:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}-${{ matrix.IS_TEST }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        IS_TEST:
          - 'true'
          - 'false'
    env:
      IS_TEST: ${{ matrix.IS_TEST }}  # Set environment variable at the job level
      IS_LOCAL: 'false'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_DATAFLOW_SERVICE_KEY }}"
      - name: Install Runner
        run: python -m pip install pangeo-forge-runner==0.10.2
      - name: Install dependencies
        run: python -m pip install -r feedstock/requirements.txt
      - name: "Expand meta for the recipes"
        run: pangeo-forge-runner expand-meta --repo=.
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ steps.auth.outputs.credentials_file_path }}"
